// Protocol buffer definitions for gRPC
// This would normally be generated by tonic-build from .proto files

// For now, we'll use placeholder types
pub mod repository_analysis {
    // Placeholder for generated proto code
}