global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'afdp-notary-service'
    static_configs:
      - targets: ['notary-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'vault'
    static_configs:
      - targets: ['vault:8200']
    metrics_path: '/v1/sys/metrics'
    params:
      format: ['prometheus']
    # Configure bearer_token via environment variable or file
    # bearer_token: 'your-token-here'
    # bearer_token_file: '/etc/prometheus/vault-token'