version: '3.8'

services:
  # HashiCorp Vault for key management
  vault:
    image: hashicorp/vault:1.15
    container_name: afdp-vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root-token-development
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./monitoring/vault-config:/vault/config
    command: server -dev
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Rekor mock server for transparency log
  rekor-mock:
    image: nginx:alpine
    container_name: afdp-rekor-mock
    ports:
      - "3000:80"
    volumes:
      - ./monitoring/rekor-mock:/usr/share/nginx/html
      - ./monitoring/nginx.conf:/etc/nginx/nginx.conf
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Temporal server for workflow orchestration
  temporal:
    image: temporalio/auto-setup:1.22.4
    container_name: afdp-temporal
    depends_on:
      - temporal-db
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=temporal-db
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    ports:
      - "7233:7233"
    volumes:
      - ./monitoring/temporal-config:/etc/temporal/config/dynamicconfig

  temporal-db:
    image: postgres:15-alpine
    container_name: afdp-temporal-db
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    ports:
      - "5432:5432"
    volumes:
      - temporal-db-data:/var/lib/postgresql/data

  temporal-admin-tools:
    image: temporalio/admin-tools:1.22.4
    container_name: afdp-temporal-admin
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    stdin_open: true
    tty: true

  temporal-web:
    image: temporalio/web:1.15.0
    container_name: afdp-temporal-web
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    ports:
      - "8088:8088"

  # Apache Pulsar for event streaming
  pulsar:
    image: apachepulsar/pulsar:3.1.0
    container_name: afdp-pulsar
    command: bin/pulsar standalone
    ports:
      - "6650:6650"
      - "8080:8080"
    volumes:
      - pulsar-data:/pulsar/data
    healthcheck:
      test: ["CMD", "bin/pulsar-admin", "brokers", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5

  # AFDP Notary Service - REST API
  notary-rest:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: afdp-notary-rest
    depends_on:
      vault:
        condition: service_healthy
      rekor-mock:
        condition: service_healthy
      temporal:
        condition: service_started
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=root-token-development
      - VAULT_TRANSIT_KEY_NAME=afdp-notary-key
      - REKOR_SERVER_URL=http://rekor-mock
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_NAMESPACE=default
      - TEMPORAL_TASK_QUEUE=afdp-notary
      - RUST_LOG=debug
      - NOTARY_LOG_FORMAT=json
    ports:
      - "3030:3030"
    command: ["./afdp-notary-rest"]
    volumes:
      - ./logs:/var/log/notary

  # AFDP Notary Service - gRPC
  notary-grpc:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: afdp-notary-grpc
    depends_on:
      vault:
        condition: service_healthy
      rekor-mock:
        condition: service_healthy
      temporal:
        condition: service_started
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=root-token-development
      - VAULT_TRANSIT_KEY_NAME=afdp-notary-key
      - REKOR_SERVER_URL=http://rekor-mock
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_NAMESPACE=default
      - TEMPORAL_TASK_QUEUE=afdp-notary
      - RUST_LOG=debug
      - NOTARY_LOG_FORMAT=json
    ports:
      - "50051:50051"
    command: ["./afdp-notary-grpc"]
    volumes:
      - ./logs:/var/log/notary

  # AFDP Notary Service - Pulsar Consumer
  notary-pulsar:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: afdp-notary-pulsar
    depends_on:
      vault:
        condition: service_healthy
      rekor-mock:
        condition: service_healthy
      pulsar:
        condition: service_healthy
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=root-token-development
      - VAULT_TRANSIT_KEY_NAME=afdp-notary-key
      - REKOR_SERVER_URL=http://rekor-mock
      - PULSAR_BROKER_URL=pulsar://pulsar:6650
      - PULSAR_TOPIC=persistent://public/default/afdp-evidence
      - RUST_LOG=debug
      - NOTARY_LOG_FORMAT=json
    command: ["./afdp-notary-pulsar"]
    volumes:
      - ./logs:/var/log/notary

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: afdp-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus-config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: afdp-grafana
    depends_on:
      - prometheus
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./monitoring/grafana-dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - grafana-data:/var/lib/grafana

  # Jaeger for distributed tracing
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: afdp-jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=9411

volumes:
  temporal-db-data:
  pulsar-data:
  prometheus-data:
  grafana-data:

networks:
  default:
    name: afdp-notary-network